### ISSUE TITLE
Extra page inserted after incremental list in beamer

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#16]
An incremental list followed on the same page by delayed text results in an extra, duplicate of the page with all list items on it, before the following text appears on the next slide. Minimal case:

```
- Ad vestibulum ornare fugiat
- consequat fringilla lacinia 

. . . 

nibh habitasse est proin tristique hendrerit. Porta facilisis scelerisque massa convallis pellentesque imperdiet imperdiet egestas conubia quisque magnis pharetra praesent tempus duis dis vestibulum morbi, pulvinar maecenas nulla fringilla. Irure dignissim laboris congue nisi commodo inceptos placerat adipisicing diam eros proident justo risus congue ultrices adipisicing pharetra potenti gravida, class nam nostra pretium.
```

**Comment by olastor** [comment]
@Jmuccigr I get the same output on my local pandoc instance (1.19.1). I don't know what the `. . .` stands for, but using `---` instead seems to output the correct result.

**Comment by Jmuccigr** [comment]
. . . tells pandoc to insert a pause on the page, so that the next element doesn't appear right away. It's basically an incremental setting for non-list-items.

But you're right, it happens to me with 2.1.1, too. Sorry I didn't check that, but I use beamer so often, I figured I would have noticed! I'll file over there.
