### ISSUE TITLE
Parameter check boxes

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#18]
pandoc's parameters are typically either on/off switches (like `--incremental`) or options (like `slide-level`). For ease of use, provide checkboxes or radio buttons to select them, instead of having the user type them in. It relieves the user of having to know or look up what the parameters are.

This could be handled by a pop-up window or just a roll-up section at the top of the page.

If you're trying to make it easy to use pandoc to generate PDFs, might as well go further!

**Comment by olastor** [comment]
Good idea!

**Comment by olastor** [comment]
Basic settings interface with checkboxes were added in #20. More settings will follow.
