### ISSUE TITLE
Losing bottom of markdown page

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#22]
Sometimes markdown content will extend off the screen, but the screen won't scroll. A resize will fix it, but then it will happen again.

Safari 11.0.3 on MacOS 10.13.3

**Comment by olastor** [comment]
Sometimes this seems to happen, if you paste a large text into the empty editor, but not always. I find this one hard to reproduce.

**Comment by olastor** [comment]
Still happens when copying a large text

**Comment by olastor** [comment]
Only on not updated dev server
