### ISSUE TITLE
Backend error

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#25]
(I'm assuming you want backend issues over here too.)

Trying to get this running locally and I run into this error:

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3002/temp/4e1d2ac0191eea22b0462ddbdff8ba38664f6a949d697ce9958040996a00d971.pdf`

The problem here is that there is no such file. Instead a perfectly fine PDF is sitting in the cache folder (cleverly called "cache" on my system), inside a folder with that nice random string as a name, and itself named "document.pdf".

**Comment by olastor** [comment]
@Jmuccigr The `temp/` folder is different from the cache directory and contains files which are exposed publicly. Every request to `localhost:3002/temp/...` will try to find a file located in the `public/` folder of the repo. Can you please look, if there is any file in it (the folder is in the same level as `server.js`, `config` and `app`)

**Comment by Jmuccigr** [comment]
Yes, it's there and it has symlinks to the PDFs. The problem was that my config file had the wrong path for the cache directory. I thought it was ok since it was making PDFs in it, but I guess not.

Is there any way to allow for relative paths in the config file? Embedding the real path seems a bit less robust. I've worked around it by putting a symlink to the actual folder in the location I put in the config file.

**Comment by olastor** [comment]
Should be fixed in https://github.com/olastor/paperify-backend/commit/3fe40b2938563578fd6683c7a45faf900720761f, can you please check?

**Comment by Jmuccigr** [comment]
Yes, that seems to work for me.

PS I see you got the command-s thing in there too!
