### ISSUE TITLE
Make location of index.html relative instead of absolute?

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#27]
The index.html file currently includes: `<base href="/">`. On my local installation, I prefer to have it in a subdirectory, so I made this into `<base href=".">`. Everything seems ok. You could even eliminate it entirely and all seems well.

Is there some reason to include it?

**Comment by olastor** [comment]
No, I think you can remove it, if it bothers you.

The `<base href="/">` was automatically created by angular-cli. According to [the docs](angular.io/guide/router#base-href) the tag seems to be needed. For your local setup it's alright to change it to `.`, but on the production website I think it should stay `/` using absolute links ("If it ain't broke, don't fix it" :) )

**Comment by Jmuccigr** [comment]
It's not that it bother me, just that having to put these files at the root level of my server is pesky. :-) I've put them into a sub-directory with no problems.
