### ISSUE TITLE
Additional command line parameters disappear.

### ISSUE THREAD

**Issue by Wandmalfarbe** [olastor/paperify#29]
The additional command line parameters disappear after closing the settings window. They are still applied and stored internally, but I can't edit them.

Steps to reproduce:

1. Enter additional command line parameters in the settings window.
2. Save and close the window.
3. Open the settings window again. The parameters are gone.

---

By the way I love this service. Great work!

**Comment by olastor** [comment]
Yes, it seems like I introduced that bug recently. Thanks for the report. It should work on https://dev.paperify.org, though (at least with a user account).

**Comment by olastor** [comment]
Fixed via 1dfff7e91c3e1c6a6175fdf28fd0ff544b664467
