### ISSUE TITLE
Native download doesn't work in Safari

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#4]
MacOS 10.13.3, Safari 11.0.3

The (right-hand-side) PDF doesn't download when I click on Safari's usual download icon on the document. The download button on the left heading does work though.

In Chromium the native PDF download method works fine.

In FireFox, the PDF doesn't even display for me.

**Comment by olastor** [comment]
Thanks for report! 

- The right side is meant for preview only. the PDF viewer gets the raw data as base64 string from the server (which might be a bit hacky). That's why there is the "normal" download button on the left.
- Which version of Firefox are you using? I'm using 58.0.1 (64Bit) on Linux and it works.

**Comment by Jmuccigr** [comment]
58.0.2 (64-bit) on a Mac. The page seems to be working, but no PDF appears.

**Comment by olastor** [comment]
@Jmuccigr Can you please recheck Firefox and Safari? The fix for #13 might has also resolved this issue.

**Comment by Jmuccigr** [comment]
@olastor, nope. Still no luck on FireFox. Safari's native download doesn't always appear right away, but it does work.

PS Did you toggle the default mode on autorenew to "off"? I think that's the right way to go.

**Comment by olastor** [comment]
@Jmuccigr Mhm, still can't reproduce the error in Firefox, maybe it's only on MacOS. Did you try clearing your browser cache or using the private mode (to confirm that FF uses the most recent version of the webapp)? Does the webconsole (CTRL+Shift+k) display any error messages?

The autorenew feature should probably be discarded (long term) to increase performance on the server. As soon as I found a way to make a `CTRL+s` command work for triggering updates, it might be better redundant.

**Comment by Jmuccigr** [comment]
Nope, even with a private window. Here's the console report with a warning upon loading the page:

```
window.controllers/Controllers is deprecated. Do not use it for UA detection.
```

**Comment by olastor** [comment]
https://stackoverflow.com/a/31768275 suggest that a browser extension might cause it to not work. Could that be the case?

**Comment by Jmuccigr** [comment]
Nope. I tried turning off all sorts of things without luck.

**Comment by olastor** [comment]
The app was rewritten in React. This issue refers to an older version.
