### ISSUE TITLE
--pdf-engine generates an error

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#5]
```
An error occurred:

pandoc: unrecognized option `--pdf-engine=xelatex'
Try pandoc --help for more information.
```

Ditto for latex-engine.

(Loving the beamer output!)

**Comment by olastor** [comment]
Yeah, the `--pdf-engine` doesn't work. That might be due to the pandoc version on the server (1.19.2.1).

But `--latex-engine` seems to work (i.e. `--latex-engine=pdflatex`). The error for `xelatex` seems to be a bug on it's own.

**Comment by olastor** [comment]
moving this to #8
