### ISSUE TITLE
Feature request: incremental lists in beamer

### ISSUE THREAD

**Issue by Jmuccigr** [olastor/paperify#7]
Support pandoc's "-i" option.

Perhaps more generally, support all of pandoc's options?

**Comment by olastor** [comment]
You're right, I didn't add many options so far because of security concerns (like accessing files on the server). But the current pandoc setup on the server runs inside a container, which can't access the filesystem, so adding all options is now possible.

**Comment by Jmuccigr** [comment]
Excellent. This would be a very handy one for me.

**Comment by Jmuccigr** [comment]
Forked and [did a PR](https://github.com/olastor/paperify-backend/pull/1) over in the backend repo.

**Comment by olastor** [comment]
Thanks, I merged it via https://github.com/olastor/paperify-backend/commit/9bc7c5516fcb44f4a5171f7563c672d3bb43b5d4
